---
# This playbook heavily based on https://github.com/amree/ansible-redmine and https://github.com/dpausp/ansible-playbook-redmine

- name: Create Redmine user
  user: name=redmine home=/var/lib/redmine generate_ssh_key=yes state=present

- name: Install system packages required for Redmine
  apt: pkg={{ item }} state=present
  with_items:
  - libapache2-mod-passenger
  - libpq-dev
  - imagemagick
  - libicu-dev
  - libmagickwand-dev
  - libxslt1-dev
  - libxml2-dev
  - liblockfile-ruby
  - libnet-ssh2-ruby

- name: Install bundler
  gem: name=bundler state=latest user_install=no

- name: Clone Redmine repository
  git: repo=https://github.com/redmine/redmine dest=/usr/share/redmine version={{ redmine_version }}

- name: Create database user for Redmine
  postgresql_user: login_host=localhost login_user={{ db_admin_username }} login_password="{{ db_admin_password }}" name={{ redmine_db_username }} password="{{ redmine_db_password }}" state=present

- name: Create database for Redmine
  postgresql_db: login_host=localhost login_user={{ db_admin_username }} login_password="{{ db_admin_password }}" name={{ redmine_db_database }} owner={{ redmine_db_username }} state=present

- name: Install Redmine configuration file
  template: src=config_configuration.yml.j2 dest=/usr/share/redmine/config/configuration.yml mode=0644 owner=redmine

- name: Install Redmine database configuration
  template: src=config_database.yml.j2 dest=/usr/share/redmine/config/database.yml mode=0644 owner=redmine

- name: Configure logs
  template: src=config_additional_environment.rb.j2 dest=/usr/share/redmine/config/additional_environment.rb mode=0644 owner=redmine

- name: Create log files
  file: path=/var/log/{{ item }} mode=0644 owner=redmine state=touch
  with_items:
  - redmine.log
  - redmine_scm_stderr.log

- name: Install required gems for Redmine
  command: /usr/local/bin/bundle install --without development test chdir=/usr/share/redmine

- name: Generate session store secret for Redmine
  command: /usr/local/bin/rake generate_secret_token chdir=/usr/share/redmine

- name: Create database schema for Redmine
  command: /usr/local/bin/rake db:migrate chdir=/usr/share/redmine
  environment:
    RAILS_ENV: production

- name: Load default data for Redmine
  command: /usr/local/bin/rake redmine:load_default_data chdir=/usr/share/redmine
  environment:
    RAILS_ENV: production
    REDMINE_LANG: "{{ redmine_language }}"

- name: Change config.ru ownership
  file: path=/usr/share/redmine/config.ru owner=redmine

- name: Change directory permissions
  file: path=/usr/share/redmine/{{ item }} owner=redmine mode=755 state=directory
  with_items:
  - public/plugin_assets
  - tmp
  - tmp/pdf

- name: Configure the Apache HTTP server for Redmine
  template: src=etc_apache2_sites-available_redmine.j2 dest=/etc/apache2/sites-available/redmine.conf group=root owner=root

- name: Enable the Redmine site
  command: a2ensite redmine.conf creates=/etc/apache2/sites-enabled/redmine.conf
  notify: restart apache
