---
# This playbook sets up j-samuel's fork of pastebin

- name: Install mercurial
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
  - mercurial

- name: Check out paste code
  hg: repo=https://bitbucket.org/j-samuel/paste dest=/var/www/paste revision=stable purge=yes

- name: Create paste configuration file
  template: src=config.php.j2 dest=/var/www/paste/config.php mode=0644 owner=root group=root

- name: Create database user for paste
  postgresql_user: login_host=localhost login_user={{ db_admin_username }} login_password="{{ db_admin_password }}" name={{ paste_db_username }} password="{{ paste_db_password }}" state=present

- name: Create database for paste
  postgresql_db: login_host=localhost login_user={{ db_admin_username }} login_password="{{ db_admin_password }}" name={{ paste_db_database }} owner={{ paste_db_username }} state=present
  notify: import sql paste

- name: Configure the Apache HTTP server for paste
  template: src=etc_apache2_sites-available_paste.j2 dest=/etc/apache2/sites-available/paste.conf group=root owner=root

- name: Enable the paste site
  command: a2ensite paste.conf creates=/etc/apache2/sites-enabled/paste.conf
  notify: restart apache
