- name: Install Postgres 9.1 and related packages
  apt: pkg={{ item }} state=installed
  with_items:
    - postgresql-9.1
    - python-psycopg2
  when: ansible_distribution_release != 'trusty'

- name: Install Postgres 9.3 and related packages for Ubuntu Trusty
  apt: pkg={{ item }} state=installed
  with_items:
    - postgresql-9.3
    - python-psycopg2
  when: ansible_distribution_release == 'trusty'

- name: Set postgres password
  command: sudo -u {{ db_admin_username }} psql -d {{ db_admin_username }} -c "ALTER USER postgres with  password '{{ db_admin_password }}';"

